language: node_js
node_js:
  - "node"
cache:
  yarn: true
env:
  global:
    - YARN_VERSION=1.7.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search