language: node_js
node_js:
  - "node"
cache:
  yarn: true
env:
  global:
    - YARN_VERSION=1.7.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH=$HOME/.yarn/bin:$PATH
after_script:
  - "yarn install coveralls && cat ./coverage/lcov.info | coveralls"
install:
  - yarn